services:
    iot_bot:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            # Mount the fastapi server
            - ./app:/rero/iot_bot/app
            
            # Expose system ports & GPIOs
            - /dev:/dev
            - /sys:/sys
        ports:
            - 8082:8082
        tty: true
        network_mode: host
